bank_project/bank/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'bank'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('<int:pk>/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', views.LoginRedirectView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/', views.AccountsView.as_view(), name='accounts'),
    path('accounts/create/', views.AccountCreateView.as_view(), name='create-account'),
    path('accounts/<int:pk>/transaction', views.DepositWithdrawView.as_view(), name='deposit-withdraw'),
    path('accounts/invalid-transaction/', TemplateView.as_view(template_name='bank/invalid-transaction.html'), name='invalid-transaction'),
    path('accounts/<int:pk>/transactions', views.TransactionsView.as_view(), name='transactions'),
    path('accounts/transfer/', views.TransferView.as_view(), name='transfer'),
    path('accounts/invalid-transfer/', TemplateView.as_view(template_name='bank/invalid-transfer.html'), name='invalid-transfer'),
    path('accounts/invalid-account/', TemplateView.as_view(template_name='bank/invalid-account.html'), name='invalid-account'),
    path('<int:pk>/edit/', views.EditProfileView.as_view(), name='edit-profile')
]

bank_project/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path('', include('bank.urls')),
    path('', include('django_prometheus.urls')),
]

bank_project/bank/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
import decimal

# Account ---------------------------------------------------------------------

class Account(models.Model):
    class Status(models.TextChoices):
        ACTIVE = 'ACTIVE', _('Active')
        INACTIVE = 'INACTIVE', _('Inactive')
        DEACTIVATED = 'DEACTIVATED', _('Deactivated')
    
    class Type(models.TextChoices):
        CHECKING = 'CHECKING', _('Checking')
        SAVINGS = 'SAVINGS', _('Savings')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=Type.choices, default=Type.CHECKING)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.INACTIVE)
    balance = models.DecimalField(max_digits=14, decimal_places=2)
    
    def __str__(self):
        return str(self.id)

# Transaction -----------------------------------------------------------------

class Transaction(models.Model):
    class Type(models.TextChoices):
        CREDIT = 'CREDIT', _('Deposit')
        DEBIT = 'DEBIT', _('Withdraw')
        TRANSFER = 'TRANSFER', _('Transfer')

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    type = models.CharField(max_length=10, choices=Type.choices)
    amount = models.DecimalField(max_digits=14, decimal_places=2, validators=[MinValueValidator(decimal.Decimal('0.01'))])
    description = models.CharField(max_length=200)

    def __str__(self):
        return str(self.id)

class Transfer(models.Model):
    source = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='transfer_sources')
    destination = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='transfer_destinations')
    date = models.DateField(auto_now_add=True)
    amount = models.DecimalField(max_digits=14, decimal_places=2, validators=[MinValueValidator(decimal.Decimal('0.01'))])
    description = models.CharField(max_length=200)

    def __str__(self):
        return str(self.id)

bank_project/bank/forms.py
import decimal
from django import forms
from django.contrib.auth.models import User

from .models import Account, Transaction, Transfer

# Register User ---------------------------------------------------------------

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput()
        }

    def register_user(self):
        user = User.objects.create_user(
            self.data['username'],
            email=self.data['email'],
            password=self.data['password'],
        )
        user.first_name = self.data['first_name']
        user.last_name = self.data['last_name']
        user.save()

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['type']
    
    def create_account(self, user):
        account = Account(
            user = user,
            balance = 0,
            status = Account.Status.INACTIVE,
            type = self.data['type']
        )
        account.save()

# Transactions ----------------------------------------------------------------

class DepositWithdrawForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['type', 'amount']
    
    def create_transaction(self, account):
        transaction = Transaction(
            account = account,
            amount = self.data['amount'],
            type = self.data['type']
        )
        if self.data['type'] == Transaction.Type.CREDIT:
            account.balance += decimal.Decimal(self.data['amount'])
            transaction.description = "Credit to account #" + str(account.id)
        else:
            account.balance -= decimal.Decimal(self.data['amount'])
            transaction.description = "Debit from account #" + str(account.id)
        transaction.save()
        account.save()

class TransferForm(forms.ModelForm):
    class Meta:
        model = Transfer
        fields = ['source', 'destination', 'amount']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TransferForm, self).__init__(*args, **kwargs)
        self.fields['source'].queryset = Account.objects.filter(user=user)
        self.fields['destination'].queryset = Account.objects.filter(user=user)
    
    def transfer(self):
        src = Account.objects.get(pk=self.data['source'])
        dest = Account.objects.get(pk=self.data['destination'])

        debit = Transaction(
            account = src,
            type = Transaction.Type.DEBIT,
            amount = decimal.Decimal(self.data['amount']),
            description = "Transfer to Account #" + str(dest.id)
        )
        src.balance -= decimal.Decimal(self.data['amount'])
        src.save()
        debit.save()
        credit = Transaction(
            account = dest,
            type = Transaction.Type.CREDIT,
            amount = decimal.Decimal(self.data['amount']),
            description = "Transfer from Account #" + str(src.id)
        )
        dest.balance += decimal.Decimal(self.data['amount'])
        dest.save()
        credit.save()

bank_project/bank/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.core.exceptions import ObjectDoesNotExist
from bank.exceptions import InvalidAccountException, InvalidTransferException

from bank.models import Account, Transaction, Transfer

from .forms import *

class LoginRedirectView(generic.RedirectView):
    permanent = True
    pattern_name = 'login'

class LogoutView(generic.RedirectView):
    permanent = True
    pattern_name = 'login'

    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/login/')

# CREATE ----------------------------------------------------------------------

class RegisterView(generic.FormView):
    template_name = 'bank/register.html'
    form_class = RegisterForm
    success_url = '/login/'

    def form_valid(self, form):
        form.register_user()
        return super().form_valid(form)

class AccountCreateView(generic.FormView):
    template_name = 'bank/account.html'
    form_class = AccountForm
    success_url = '/accounts/'

    def form_valid(self, form):
        form.create_account(self.request.user)
        return super().form_valid(form)

# READ ------------------------------------------------------------------------

class AccountsView(generic.ListView):
    template_name = 'bank/accounts.html'
    context_object_name = 'account_list'

    def get_queryset(self):
        return Account.objects.filter(user=self.request.user)

class TransactionsView(generic.ListView):
    template_name = 'bank/transactions.html'
    context_object_name = 'transaction_list'

    def get_queryset(self):
        account = Account.objects.get(pk=self.kwargs.get('pk'))
        return Transaction.objects.filter(account=account)


# UPDATE ----------------------------------------------------------------------

class EditProfileView(generic.UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    widgets = {
        'password': forms.PasswordInput()
    }
    success_url = '/'

# DEPOSIT/WITHDRAW/TRANSFER ---------------------------------------------------

class DepositWithdrawView(generic.FormView):
    template_name = 'bank/deposit-withdraw.html'
    form_class = DepositWithdrawForm
    success_url = '/accounts/'

    def form_valid(self, form):
        account = Account.objects.get(pk=self.kwargs.get('pk'))
        if account.status != Account.Status.ACTIVE:
            raise InvalidAccountException
        form.create_transaction(account)
        return super().form_valid(form)

class TransferView(generic.CreateView):
    template_name = 'bank/transfer.html'
    form_class = TransferForm
    success_url = '/accounts/'

    def get_form_kwargs(self):
        kwargs = super(TransferView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        source = Account.objects.get(pk=form.data.get('source'))
        print("Source: " + str(source))
        destination = Account.objects.get(pk=form.data.get('destination'))
        print("Destination: " + str(source))

        if source.status != Account.Status.ACTIVE:
            # raise InvalidAccountException
            return HttpResponseRedirect('/accounts/invalid-transaction/')
        if destination.status != Account.Status.ACTIVE:
            # raise InvalidTransferException
            return HttpResponseRedirect('/accounts/invalid-transfer/')
        if source == destination:
            # raise InvalidTransferException
            return HttpResponseRedirect('/accounts/invalid-transfer')
        try:
            user = self.request.user
            form.transfer()
            return super().form_valid(form)
        except ObjectDoesNotExist:
            return HttpResponseRedirect('/accounts/invalid-account')

bank_project/bank/templates/bank/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Account</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Account">
    </form>
    <button onclick="location.href='/accounts/';">Back</button>
</body>
</html>

bank_project/bank/templates/bank/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accounts</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <h1>Accounts</h1>
    <span>
        <a name="action-button" href="create/">Create Account</a>
        <a name="action-button" href="/accounts/transfer/">Transfer</a>    
    </span>
    {% if account_list %}
        {% for account in account_list %}
        <div name="account-block">
            <div name="account-info">
                <h3 name="info-header">Account Number: {{ account.id }}</h4>
                <p>Type: {{ account.type }}</p>
                <p>Status: {{ account.status }}</p>
                <p>Balance: ${{ account.balance }}</p>
            </div>
            <span name="account-actions-list">
                <a name="action-button" href="{% url 'bank:deposit-withdraw' account.id %}">Deposit/Withdraw</a>
                <a name="action-button" href="{% url 'bank:transactions' account.id %}">View Transactions</a>
            </span>    
        </div>
        {% endfor %}
    {% else %}
        <p>No accounts have been created</p>
    {% endif %}
</body>
</html>

bank_project/bank/templates/bank/deposit-withdraw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <h1>Deposit/Withdraw</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <button onclick="history.back()">Back</button>
</body>
</html>

bank_project/bank/templates/bank/deposit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deposit</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <h1>Deposit</h1>
    {% if account.is_active %}
        <p>Hello World</p>
    {% else %}
        <p>You cannot perform transactions for non-active accounts.</p>
    {% endif %}
    <button onclick="history.back()">Back</button>
</body>
</html>

bank_project/bank/templates/bank/invalid-account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invalid Account</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <br>
    <p>The account you entered does not exist. Please try again.</p>
    <br>
    <button onclick="history.back()">Back</button>
    <button onclick="location.href = '/accounts/';">Back</button>
</body>
</html>

bank_project/bank/templates/bank/invalid-transaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Non-Active Account</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <br>
    <p>You cannot perform transactions on a non-active account.</p>
    <br>
    <button onclick="history.back()">Back</button>
    <button onclick="location.href = '/accounts/';">Back</button>
</body>
</html>

bank_project/bank/templates/bank/invalid-transfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invalid Tranfer</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
    <br>
    <p>The destination account cannot be inactive, deactivated, or the same as the source account</p>
    <br>
    <button onclick="history.back()">Back</button>
    <button onclick="location.href = '/accounts/';">Back</button>
</body>
</html>

bank_project/bank/templates/bank/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
    <button onclick="location.href = '/login/';">Back</button>
</body>
</html>

bank_project/bank/templates/bank/transactions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transactions</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
    <h1>Transactions</h1>
    {% if transaction_list %}
        <table>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Type</th>
                <th>Description</th>
            </tr>
            {% for transaction in transaction_list %}
                <tr>
                    <td>{{ transaction.date }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.type }}</td>
                    <td>{{ transaction.description }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>This account has no transactions.</p>
    {% endif %}
    <button onclick="history.back()">Back</button>
</body>
</html>

bank_project/bank/templates/bank/transfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../../static/bank/styles.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transfer</title>
</head>
<body>
    <span name="navbar">
        <a name="navbar-item" href="/">Home</a>
        <a name="navbar-item" href="/logout">Log Out</a>
    </span>
        <h1>Transfer</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <!-- <a href="/accounts/">Back</a> -->
    <button onclick="location.href = '/accounts/';">Back</button>
</body>
</html>